name: minimal
channels:
- anaconda
- conda-forge
dependencies:
- python=3.11
- pip=22.1.2
- pip:
  - transformers==4.37.2
  - accelerate==0.23.0
  - bitsandbytes==0.41.1
  - datasets
  - peft==0.5.0
  - scikit-learn==1.3.1
  - sentencepiece==0.1.99
  - trl==0.7.2
  - protobuf==3.20.3
  - wandb==0.15.12
  - onnxruntime-gpu==1.17.1
  - --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-genai/pypi/simple/
  - onnxruntime-genai-cuda==0.3.0rc2
  - onnxscript
  - einops
  - git+https://github.com/microsoft/Olive
  - azure-keyvault==4.2.0
  - azure-identity==1.17.0