name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pip:
    - --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-genai/pypi/simple/
    - onnxruntime-genai-cuda
