$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: lora-endpoint
model: azureml:lora-model_gpu-cuda_1:1
code_configuration:
  code: src
  scoring_script: score.py
environment: azureml:ort-genai:3
instance_type: Standard_NC12s_v3
instance_count: 1
